dependencies:
- name: demo142
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: godemo8
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodey28
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: reactiscool
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
