dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: my-spring-boot-prometheus
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: demo67
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mynode1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mynode2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
