dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.71
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.71
- name: jxrocks
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
