dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: demo108
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: bdd-test-golang-http-1530530042
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-python-http-1530530042
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-aspnet-app-1530530042
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-node-http-1530530042
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-rust-http-1530530042
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
