dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: demo52
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: demo-55
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
