dependencies:
- name: demo167
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: demo168
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: demo258
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.82
